HOTELS_COLLECTION_NAME = "hotels"
CITIES_COLLECTION_NAME = "cities"
REVIEWS_COLLECTION_NAME = "reviews"
REVIEW_VECTOR_COLLECTION_NAME = "hotel_reviews_embeddings"
USERS_COLLECTION_NAME = "users"
FEATURED_VOTE_THRESHOLD = 13
