HOTELS_COLLECTION_NAME = "hotels"
CITIES_COLLECTION_NAME = "cities"
REVIEWS_COLLECTION_NAME = "reviews"
REVIEW_VECTOR_COLLECTION_NAME = "hotel_reviews_embeddings"
USERS_COLLECTION_NAME = "users"
LLM_CACHE_COLLECTION_NAME = "llm_cache"

FEATURED_VOTE_THRESHOLD = 13
MAX_NUM_REVIEWS_TO_COUNT = 50
